### PR TITLE
Add cordova integration

### PR DESCRIPTION
**Pull request by nerdmed**
It seemes like the `visibilitychange` event does not trigger when you leave the app on an iPad or android Device. Therefore i have added 2 more listener to support cordova apps.

What do you think any feedback?

### CODE REVIEW

**Comment by bradvogel** [comment]
thanks!

**Comment by nerdmed** [comment]
@bradvogel thanks for merging so quickly! Would be great if you could release this version to atmosphere, i have changed the version to `0.0.3 `in the PR

**Comment by bradvogel** [comment]
published https://atmospherejs.com/mixmax/smart-disconnect

**Comment by nerdmed** [comment]
cool thx!

**Pull request merged**
